# Generated by Django 4.2.4 on 2023-11-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasahorroscreditos',
            name='estado',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='personasahorroscreditos',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.grupos'),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='aportes_anteriores',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='aportes_pendientes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='aportes_por_pagar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='aportes_recibidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='retiro_de_aportes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='saldo_aportes_por_pagar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahorros',
            name='total_de_aportes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='abono_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='credito_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='cuota_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='interes_anterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='interes_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='intereses_recibidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='nota',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='nueva_afiliacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='saldo_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='saldo_intereses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='solicitud_de_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='total_interes_a_pagar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='total_recibido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='valor_credito_solicitado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='valor_cuota_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personasahorroscreditos',
            name='fecha',
            field=models.CharField(max_length=45),
        ),
    ]
