# Generated by Django 4.2.4 on 2023-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_personasahorroscreditos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='fecha_final',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='fecha_inicio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='nueva_afiliacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
